---
- name: Install and configure Nginx web server with Fluentd
  become: true
  hosts: all
  tasks:
    # importing the variables
    - name: Include defaults variables
      ansible.builtin.include_vars:
        file: ../defaults/main.yml
  
    # updating the apt cache
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
  
    # importing the firewall installation task
    - import_tasks: firewall.yml
      tags: firewall
    
    # importing the nginx installation task
    - import_tasks: nginx.yml
      tags: nginx
    
    # importing the fluentd installation task
    - import_tasks: fluentd.yml
      tags: fluentd
